# DEPRECATED as of version 1.2.2.RELEASE - use the src/kubernetes/kafka/kafka-zk-deployment.yaml file instead
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka-zk
    component: kafka-zk
  name: kafka-zk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-zk
        component: kafka-zk
    spec:
      containers:
      - name: kafka-zk
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: kafka-zk