apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        ports:
        - containerPort: 9092
        - containerPort: 2181
        env:
        - name: ADVERTISED_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ADVERTISED_PORT
          value: '9092'
