apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    spring-cloud-service: kafka
spec:
  type: LoadBalancer
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zk
  labels:
    spring-cloud-service: zk
spec:
  type: LoadBalancer
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    name: kafka
