# DEPRECATED as of version 1.2.2.RELEASE - use the src/kubernetes/metrics/metrics-deployment-rabbit.yaml file instead
apiVersion: v1
kind: ReplicationController
metadata:
  name: metrics
spec:
  replicas: 1
  selector:
    name: metrics
  template:
    metadata:
      labels:
        name: metrics
    spec:
      containers:
      - name: metrics
        image: springcloud/metrics-collector-rabbit:1.0.0.RELEASE
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1.0
            memory: 2048Mi
          requests:
            cpu: 0.5
            memory: 1024Mi
        env:
        - name: SERVER_PORT
          value: '80'
        - name: SECURITY_BASIC_ENABLED
          value: 'false'
        - name: SPRING_RABBITMQ_HOST
          value: '${RABBITMQ_SERVICE_HOST}'
        - name: SPRING_RABBITMQ_PORT
          value: '${RABBITMQ_SERVICE_PORT}'
