# DEPRECATED as of version 1.2.2.RELEASE - use the src/kubernetes/mysql/mysql-svc.yaml file instead
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
spec:
# Use "LoadBalancer" if you want an external IP for your service to connect from external tools
  type: LoadBalancer
  ports:
    - port: 3306
  selector:
    name: mysql
