apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
spec:
# Use "LoadBalancer" if you want an external IP for your service to connect from external tools
  type: LoadBalancer
  ports:
    - port: 3306
  selector:
    name: mysql