apiVersion: v1
kind: Service
metadata:
  labels:
    spring-cloud-service: rabbitmq
  name: rabbitmq
spec:
# Use "LoadBalancer" if you want an external IP for your service to connect from external tools
#  type: LoadBalancer
  ports:
  - port: 5672
  selector:
    name: rabbitmq
