# DEPRECATED as of version 1.2.2.RELEASE - use the src/kubernetes/rabbitmq/rabbitmq-deployment.yaml file instead
apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
