apiVersion: v1
kind: Service
metadata:
  labels:
    spring-cloud-service: rabbitmq
  name: rabbitmq
spec:
# If you are not running k8s on a local dev box, use LoadBalancer to expose the (changing) Redis pod to the k8s API
#  type: LoadBalancer
  ports:
  - port: 5672
  selector:
    name: rabbitmq
