# DEPRECATED as of version 1.2.2.RELEASE - use the src/kubernetes/redis/redis-svc.yaml file instead
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    spring-cloud-service: redis
spec:
# Use "LoadBalancer" if you want an external IP for your service to connect from external tools
#  type: LoadBalancer
  ports:
    - port: 6379
  selector:
    name: redis
