kind: Service
apiVersion: v1
metadata:
  name: scdf
  labels:
    spring-cloud-service: scdf
spec:
# If you are not running k8s on a local dev box, use LoadBalancer to expose the (changing) Redis pod to the k8s API
  type: LoadBalancer
  ports:
    - port: 9393
  selector:
    name: scdf
