# DEPRECATED as of version 1.2.2.RELEASE - use the src/kubernetes/mysql/mysql-secrets.yaml file instead
apiVersion: v1
kind: Secret
metadata:
  name: scdf-secrets
data:
  spring.datasource.username: cm9vdA==
  spring.datasource.password: eW91cnBhc3N3b3Jk
