# DEPRECATED as of version 1.2.2.RELEASE - use the src/kubernetes/server/server-svc.yaml file instead
kind: Service
apiVersion: v1
metadata:
  name: scdf
  labels:
    spring-cloud-service: scdf
spec:
  # If you are running k8s on a local dev box, you can use type NodePort instead
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: scdf
