kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scdf-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "replicationcontrollers", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets", "jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
