[[server]]
= Admin Server

== Admin Server Properties

The Kubernetes Admin Server has several properties you can configure that let you control the default values for where to pull artifacts from maven and to set the `cpu` and `memory` requirements for the pod.  The configuration is controlled by configuration properties under the `kubernetes` prefix.  For example you might declare the following section in an `application.properties` file or pass them as command line arguments when starting the Admin Server.
```
kubernetes.memory=512Mi
kubernetes.cpu=500m
```

See https://github.com/spring-cloud/spring-cloud-dataflow-admin-kubernetes/blob/master/spring-cloud-dataflow-admin-kubernetes/src/main/java/org/springframework/cloud/dataflow/module/deployer/kubernetes/KubernetesModuleDeployerProperties.java[KubernetesModuleDeployerProperties] for more of the supported options.

Admin Server properties that are common across all of the Data Flow Admin Server implementations that concern maven repository settings can also be set in a similar manner.  See the section on Common Admin Server Properties for more information.

