[appendix]
[[howto]]
= "`How-to`" guides

This section provides answers to some common "`how do I do that...`" type of questions
that often arise when developers use Spring Cloud Data Flow.

If you have a specific problem that we don't cover here, you might want to check out
http://stackoverflow.com/tags/spring-cloud-dataflow[stackoverflow.com] to see if someone has
already provided an answer. Stack Overflow is also a great place to ask new questions (please use
the `spring-cloud-dataflow` tag).

We are also more than happy to extend this section. If you want to add a "`how-to`", you
can send us a {github-code}[pull request].

== Logging

Spring Cloud Data Flow is built upon several Spring projects, but ultimately the dataflow-server is a
Spring Boot app, so the logging techniques that apply to any link:http://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html#howto-logging[Spring Boot]
application are applicable here as well.

While troubleshooting, the following are the two primary areas where enabling the DEBUG logs could be useful.

* <<howto-deployment-logs>>
* <<howto-application-logs>>

[[howto-deployment-logs]]
=== Deployment Logs
Spring Cloud Data Flow builds upon the link:https://github.com/spring-cloud/spring-cloud-deployer[Spring Cloud Deployer] SPI. The platform-specific dataflow-server uses the respective link:https://github.com/spring-cloud?utf8=%E2%9C%93&query=deployer[SPI implementations].
Specifically, if you want to troubleshoot deployment-specific issues (such as the network errors), it helps
to enable the DEBUG logs at the underlying deployer and the libraries used by it.

For instance, if you want to enable DEBUG logs for the link:https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/tree/master/spring-cloud-deployer-kubernetes[kubernetes-deployer],
start the server with following environment variable:

====
[source,bash]
----
LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_DEPLOYER_SPI_KUBERNETES=DEBUG
----
====

[[howto-application-logs]]
=== Application Logs

The streaming applications in Spring Cloud Data Flow are Spring Boot applications, and you can set them up
independently with logging configurations.

For instance, if you need to troubleshoot the `header` and `payload` specifics that are being passed
around source, processor, and sink channels, you can deploy the stream with the following
options:

====
[source,bash]
----
dataflow:>stream create foo --definition "http --logging.level.org.springframework.integration=DEBUG | transform --logging.level.org.springframework.integration=DEBUG | log --logging.level.org.springframework.integration=DEBUG" --deploy
----

where `org.springframework.integration` is the global package for everything related to Spring Integration,
which is responsible for messaging channels
====

You can also specify these properties with `deployment` properties when you deploy the stream, as the following example shows:

====
[source,bash]
----
dataflow:>stream deploy foo --properties "app.*.logging.level.org.springframework.integration=DEBUG"
----
====
