[[streams-using-skipper]]
= Streams deployed using Skipper

We will proceed with the assumption that Spring Cloud Data Flow, <<getting-started.adoc#spring-cloud-skipper-integration, Spring Cloud Skipper>>, RDBMS, and desired messaging 
middleware is up and running in minikube. In this section we will use RabbitMQ as the messaging middleware. The same concepts and steps apply for Kafka as well, except Kafka based binder Docker images would be used as described in <<getting-started.adoc#getting-started-create-stream-without-skipper, Create Streams without Skipper>>.

[source,console,options=nowrap]
----
$ kubectl get all
NAME                              READY     STATUS    RESTARTS   AGE
po/mysql-777890292-z0dsw          1/1       Running   0          38m
po/rabbitmq-317767540-2qzrr       1/1       Running   0          38m
po/redis-4054078334-37m0l         1/1       Running   0          38m
po/scdf-server-2734071167-bjd3g   1/1       Running   0          48s
po/skipper-2408247821-50z31       1/1       Running   0          3m

...
...
----

To start the Data Flow Shell for the Data Flow server running in `skipper` mode:

[source,bash,subs=attributes]
----
$ java -jar spring-cloud-dataflow-shell-{dataflow-project-version}.jar --dataflow.mode=skipper
----
If the Data Flow Server and shell are not running on the same host, point the shell to the Data Flow server URL.

Use the `kubectl get svc scdf-server` command to locate the EXTERNAL_IP address assigned to `scdf-server`, we will use that to connect from the shell.

```
$ kubectl get svc scdf-server
NAME         CLUSTER-IP       EXTERNAL-IP       PORT(S)    AGE
scdf-server  10.103.246.82    130.211.203.246   80/TCP     4m
```
So the URL you need to use is in this case http://130.211.203.246

If you are using Minikube then you don't have an external load balancer and the EXTERNAL-IP will show as `<pending>`. You need to use the NodePort assigned for the `skipper` service. Use this command to look up the URL to use:

```
$ minikube service --url scdf-server
http://192.168.99.100:31991
```

Configure the Data Flow server URI with the following command using the default user and password settings:

[source,console,options=nowrap]
----
server-unknown:>dataflow config server --username user --password password --uri http://130.211.203.246
Successfully targeted http://130.211.203.246
dataflow:>
----
Alternatively, pass in the command line option `--dataflow.uri`.  The shell's command line option `--help` shows what is available.


Verify the registered platforms in Skipper.

[source,console,options=nowrap]
----
dataflow:>stream platform-list
╔════════╤══════════╤════════════════════════════════════════════════════════════════════════════════════════════════╗
║  Name  │   Type   │                                      Description                                               ║
╠════════╪══════════╪════════════════════════════════════════════════════════════════════════════════════════════════╣
║minikube│kubernetes│master url = [https://kubernetes.default.svc/], namespace = [default], api version = [v1]       ║
╚════════╧══════════╧════════════════════════════════════════════════════════════════════════════════════════════════╝
----

Let's start with deploying a stream with the `time-source` pointing to 1.3.0.RELEASE and `log-sink` pointing
to 1.2.0.RELEASE. The goal is to rolling upgrade the `log-sink` application to 1.3.0.RELEASE.

[source,console,options=nowrap]
----
dataflow:>app register --type source --name time --uri docker://springcloudstream/time-source-rabbit:1.3.0.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:time-source-rabbit:jar:metadata:1.3.0.RELEASE
Successfully registered application 'source:time'

dataflow:>app register --type sink --name log --uri docker://springcloudstream/log-sink-rabbit:1.2.0.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:jar:metadata:1.2.0.RELEASE
Successfully registered application 'sink:log'

dataflow:>app info time --type source
Information about source application 'time':
Version: '1.3.0.RELEASE':
Default application version: 'true':
Resource URI: docker://springcloudstream/time-source-rabbit:1.3.0.RELEASE
╔══════════════════════════════╤══════════════════════════════╤══════════════════════════════╤══════════════════════════════╗
║         Option Name          │         Description          │           Default            │             Type             ║
╠══════════════════════════════╪══════════════════════════════╪══════════════════════════════╪══════════════════════════════╣
║trigger.time-unit             │The TimeUnit to apply to delay│<none>                        │java.util.concurrent.TimeUnit ║
║                              │values.                       │                              │                              ║
║trigger.fixed-delay           │Fixed delay for periodic      │1                             │java.lang.Integer             ║
║                              │triggers.                     │                              │                              ║
║trigger.cron                  │Cron expression value for the │<none>                        │java.lang.String              ║
║                              │Cron Trigger.                 │                              │                              ║
║trigger.initial-delay         │Initial delay for periodic    │0                             │java.lang.Integer             ║
║                              │triggers.                     │                              │                              ║
║trigger.max-messages          │Maximum messages per poll, -1 │1                             │java.lang.Long                ║
║                              │means infinity.               │                              │                              ║
║trigger.date-format           │Format for the date value.    │<none>                        │java.lang.String              ║
╚══════════════════════════════╧══════════════════════════════╧══════════════════════════════╧══════════════════════════════╝

dataflow:>app info log --type sink
Information about sink application 'log':
Version: '1.2.0.RELEASE':
Default application version: 'true':
Resource URI: docker://springcloudstream/log-sink-rabbit:1.2.0.RELEASE
╔══════════════════════════════╤══════════════════════════════╤══════════════════════════════╤══════════════════════════════╗
║         Option Name          │         Description          │           Default            │             Type             ║
╠══════════════════════════════╪══════════════════════════════╪══════════════════════════════╪══════════════════════════════╣
║log.name                      │The name of the logger to use.│<none>                        │java.lang.String              ║
║log.level                     │The level at which to log     │<none>                        │org.springframework.integratio║
║                              │messages.                     │                              │n.handler.LoggingHandler$Level║
║log.expression                │A SpEL expression (against the│payload                       │java.lang.String              ║
║                              │incoming message) to evaluate │                              │                              ║
║                              │as the logged message.        │                              │                              ║
╚══════════════════════════════╧══════════════════════════════╧══════════════════════════════╧══════════════════════════════╝
----


. Create stream.

+
```
dataflow:>stream create foo --definition "time | log"
Created new stream 'foo'
```
+

. Deploy stream.

+
```
dataflow:>stream deploy foo --platformName minikube
Deployment request has been sent for stream 'foo'
```
+

[NOTE]
====
While deploying the stream, we are supplying `--platformName` and that indicates the platform repository (i.e., `minikube`) to
use when deploying the stream applications via Skipper.
====

. List pods.

+
[source,console,options=nowrap]
----
$ kubectl get pods
NAME                              READY     STATUS    RESTARTS   AGE
foo-log-v1-0-2k4r8             1/1       Running   0          2m
foo-time-v1-qhdqq              1/1       Running   0          2m
mysql-777890292-z0dsw          1/1       Running   0          49m
rabbitmq-317767540-2qzrr       1/1       Running   0          49m
redis-4054078334-37m0l         1/1       Running   0          49m
scdf-server-2734071167-bjd3g   1/1       Running   0          12m
skipper-2408247821-50z31       1/1       Running   0          15m

...
...
----
+

. Verify logs.

+
[source,console,options=nowrap]
----
$ kubectl logs -f foo-log-v1-0-2k4r8
...
...
2017-10-30 22:59:04.966  INFO 1 --- [ foo.time.foo-1] log-sink                                 : 10/30/17 22:59:04
2017-10-30 22:59:05.968  INFO 1 --- [ foo.time.foo-1] log-sink                                 : 10/30/17 22:59:05
2017-10-30 22:59:07.000  INFO 1 --- [ foo.time.foo-1] log-sink                                 : 10/30/17 22:59:06
----
+

. Verify the stream history.

+
[source,console,options=nowrap]
----
dataflow:>stream history --name foo
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║1      │Mon Oct 30 16:18:28 PDT 2017│DEPLOYED│foo         │1.0.0          │Install complete║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
----
+

. Verify the package manifest. The `log-sink` should be at 1.2.0.RELEASE.

+
[source,yml,options=nowrap]
----
dataflow:>stream manifest --name foo

---
# Source: log.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "log"
spec:
  resource: "docker:springcloudstream/log-sink-rabbit"
  resourceMetadata: "docker:springcloudstream/log-sink-rabbit:jar:metadata:1.2.0.RELEASE"
  version: "1.2.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "log"
    "spring.cloud.stream.metrics.key": "foo.log.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.input.group": "foo"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.dataflow.stream.name": "foo"
    "spring.cloud.dataflow.stream.app.type": "sink"
    "spring.cloud.stream.bindings.input.destination": "foo.time"
  deploymentProperties:
    "spring.cloud.deployer.group": "foo"

---
# Source: time.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "time"
spec:
  resource: "docker:springcloudstream/time-source-rabbit"
  resourceMetadata: "docker:springcloudstream/time-source-rabbit:jar:metadata:1.3.0.RELEASE"
  version: "1.3.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "time"
    "spring.cloud.stream.metrics.key": "foo.time.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.output.producer.requiredGroups": "foo"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.stream.bindings.output.destination": "foo.time"
    "spring.cloud.dataflow.stream.name": "foo"
    "spring.cloud.dataflow.stream.app.type": "source"
  deploymentProperties:
    "spring.cloud.deployer.group": "foo"
----
+

. Let's register `log-sink` application version 1.3.0.RELEASE and update our stream to use it

+
[source,console,options=nowrap]
----
dataflow:>app register --name log --type sink --uri docker:springcloudstream/log-sink-rabbit:1.3.0.RELEASE --force
Successfully registered application 'sink:log'

dataflow:>stream update --name foo --properties version.log=1.3.0.RELEASE
Update request has been sent for stream 'foo'
----
+

. List pods.

+
[source,console,options=nowrap]
----
$ kubectl get pods
NAME                              READY     STATUS        RESTARTS   AGE
foo-log-v1-0-2k4r8             1/1       Terminating   0          3m
foo-log-v2-0-fjnlt             0/1       Running       0          9s
foo-time-v1-qhdqq              1/1       Running       0          3m
mysql-777890292-z0dsw          1/1       Running       0          51m
rabbitmq-317767540-2qzrr       1/1       Running       0          51m
redis-4054078334-37m0l         1/1       Running       0          51m
scdf-server-2734071167-bjd3g   1/1       Running       0          14m
skipper-2408247821-50z31       1/1       Running       0          16m

...
...
----
+

[NOTE]
====
Notice that there are two versions of the `log-sink` applications. The `foo-log-v1-0-2k4r8` pod is going down and the
newly spawned `foo-log-v2-0-fjnlt` pod is bootstrapping.  The version number is incremented and  the version-number
(`v2`) is included in the new application name.
====

. Once the new pod is up and running, let's verify the logs.

+
[source,console,options=nowrap]
----
$ kubectl logs -f foo-log-v2-0-fjnlt
...
...
2017-10-30 23:24:30.016  INFO 1 --- [ foo.time.foo-1] log-sink                                 : 10/30/17 23:24:30
2017-10-30 23:24:31.017  INFO 1 --- [ foo.time.foo-1] log-sink                                 : 10/30/17 23:24:31
2017-10-30 23:24:32.018  INFO 1 --- [ foo.time.foo-1] log-sink                                 : 10/30/17 23:24:32
----
+

. Let's look at the updated package manifest persisted in Skipper. We should now be seeing `log-sink` at 1.3.0.RELEASE.

+
[source,yml,options=nowrap]
----
dataflow:>stream manifest --name foo

---
# Source: log.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "log"
spec:
  resource: "docker:springcloudstream/log-sink-rabbit"
  resourceMetadata: "docker:springcloudstream/log-sink-rabbit:jar:metadata:1.3.0.RELEASE"
  version: "1.3.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "log"
    "spring.cloud.stream.metrics.key": "foo.log.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.input.group": "foo"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.dataflow.stream.name": "foo"
    "spring.cloud.dataflow.stream.app.type": "sink"
    "spring.cloud.stream.bindings.input.destination": "foo.time"
  deploymentProperties:
    "spring.cloud.deployer.group": "foo"
    "spring.cloud.deployer.count": "1"

---
# Source: time.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "time"
spec:
  resource: "docker:springcloudstream/time-source-rabbit"
  resourceMetadata: "docker:springcloudstream/time-source-rabbit:jar:metadata:1.3.0.RELEASE"
  version: "1.3.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "time"
    "spring.cloud.stream.metrics.key": "foo.time.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.output.producer.requiredGroups": "foo"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.stream.bindings.output.destination": "foo.time"
    "spring.cloud.dataflow.stream.name": "foo"
    "spring.cloud.dataflow.stream.app.type": "source"
  deploymentProperties:
    "spring.cloud.deployer.group": "foo"
----
+

. Verify stream history for the latest updates.

+
[source,console,options=nowrap]
----
dataflow:>stream history --name foo
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║2      │Mon Oct 30 16:21:55 PDT 2017│DEPLOYED│foo         │1.0.0          │Upgrade complete║
║1      │Mon Oct 30 16:18:28 PDT 2017│DELETED │foo         │1.0.0          │Delete complete ║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
----
+

. Rolling-back to the previous version is just a command away.

+
[source,console,options=nowrap]
----
dataflow:>stream rollback --name foo
Rollback request has been sent for the stream 'foo'

...
...

dataflow:>stream history --name foo
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║3      │Mon Oct 30 16:22:51 PDT 2017│DEPLOYED│foo         │1.0.0          │Upgrade complete║
║2      │Mon Oct 30 16:21:55 PDT 2017│DELETED │foo         │1.0.0          │Delete complete ║
║1      │Mon Oct 30 16:18:28 PDT 2017│DELETED │foo         │1.0.0          │Delete complete ║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
----
