[[streams-using-skipper]]
= Deploying Streams by Using Skipper

This section assumes that Spring Cloud Data Flow, <<getting-started.adoc#spring-cloud-skipper-integration, Spring Cloud Skipper>>, an RDBMS, and your desired messaging  middleware is up and running in minikube. We use RabbitMQ as the messaging middleware. The same concepts and steps apply for Kafka. <<getting-started.adoc#getting-started-create-stream-without-skipper>> describes how to use Kafka-based Docker images.

Before you get started, you can see what applications are running. The following example (with output) shows how to do so:

====
[source,console,options=nowrap]
----
$ kubectl get all
NAME                              READY     STATUS    RESTARTS   AGE
po/mysql-777890292-z0dsw          1/1       Running   0          38m
po/rabbitmq-317767540-2qzrr       1/1       Running   0          38m
po/redis-4054078334-37m0l         1/1       Running   0          38m
po/scdf-server-2734071167-bjd3g   1/1       Running   0          48s
po/skipper-2408247821-50z31       1/1       Running   0          3m

...
...
----
====

The following example shows how to start the Data Flow Shell for the Data Flow server running in `skipper` mode:

====
[source,bash,subs=attributes]
----
$ java -jar spring-cloud-dataflow-shell-{dataflow-project-version}.jar --dataflow.mode=skipper
----
====

If the Data Flow Server and shell do not run on the same host, point the shell to the Data Flow server URL. To do so, you can use the `kubectl get svc scdf-server` command to locate the EXTERNAL-IP address assigned to `scdf-server` and use that to connect from the shell. The following example (with output) shows how to get the external IP address (and other details):

====
[source]
----
kubectl get svc scdf-server
NAME         CLUSTER-IP       EXTERNAL-IP       PORT(S)    AGE
scdf-server  10.103.246.82    130.211.203.246   80/TCP     4m
----
====

In the preceding example, the URL to use is http://130.211.203.246

If you use Minikube, you do not have an external load balancer and the EXTERNAL-IP column shows `<pending>`. You need to use the NodePort assigned for the `skipper` service. The following example (with output) shows how to look up the URL to use:

====
[source]
----
$ minikube service --url scdf-server
http://192.168.99.100:31991
----
====

The following example (with output) shows how to configure the Data Flow server URI (with the default user and password settings):

====
[source,console,options=nowrap]
----
server-unknown:>dataflow config server --username user --password password --uri http://130.211.203.246
Successfully targeted http://130.211.203.246
dataflow:>
----
====

Alternatively, you can use the `--dataflow.uri` command line option.  The shell's `--help` command line option shows what is available.

Then you can verify the registered platforms in Skipper, as the following example (with output) shows:

====
[source,console,options=nowrap]
----
dataflow:>stream platform-list
╔════════╤══════════╤════════════════════════════════════════════════════════════════════════════════════════════════╗
║  Name  │   Type   │                                      Description                                               ║
╠════════╪══════════╪════════════════════════════════════════════════════════════════════════════════════════════════╣
║minikube│kubernetes│master url = [https://kubernetes.default.svc/], namespace = [default], api version = [v1]       ║
╚════════╧══════════╧════════════════════════════════════════════════════════════════════════════════════════════════╝
----
====

We start by deploying a stream with the `time-source` pointing to the 1.3.0.RELEASE and `log-sink` pointing
to the 1.2.0.RELEASE. The goal is to perform a rolling upgrade of the `log-sink` application to 1.3.0.RELEASE. The following mult-step example (with output after each command) shows how to do so:

====
[source,console,options=nowrap]
----
dataflow:>app register --type source --name time --uri docker://springcloudstream/time-source-rabbit:1.3.0.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:time-source-rabbit:jar:metadata:1.3.0.RELEASE
Successfully registered application 'source:time'

dataflow:>app register --type sink --name log --uri docker://springcloudstream/log-sink-rabbit:1.2.0.RELEASE --metadata-uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:jar:metadata:1.2.0.RELEASE
Successfully registered application 'sink:log'

dataflow:>app info time --type source
Information about source application 'time':
Version: '1.3.0.RELEASE':
Default application version: 'true':
Resource URI: docker://springcloudstream/time-source-rabbit:1.3.0.RELEASE
╔══════════════════════════════╤══════════════════════════════╤══════════════════════════════╤══════════════════════════════╗
║         Option Name          │         Description          │           Default            │             Type             ║
╠══════════════════════════════╪══════════════════════════════╪══════════════════════════════╪══════════════════════════════╣
║trigger.time-unit             │The TimeUnit to apply to delay│<none>                        │java.util.concurrent.TimeUnit ║
║                              │values.                       │                              │                              ║
║trigger.fixed-delay           │Fixed delay for periodic      │1                             │java.lang.Integer             ║
║                              │triggers.                     │                              │                              ║
║trigger.cron                  │Cron expression value for the │<none>                        │java.lang.String              ║
║                              │Cron Trigger.                 │                              │                              ║
║trigger.initial-delay         │Initial delay for periodic    │0                             │java.lang.Integer             ║
║                              │triggers.                     │                              │                              ║
║trigger.max-messages          │Maximum messages per poll, -1 │1                             │java.lang.Long                ║
║                              │means infinity.               │                              │                              ║
║trigger.date-format           │Format for the date value.    │<none>                        │java.lang.String              ║
╚══════════════════════════════╧══════════════════════════════╧══════════════════════════════╧══════════════════════════════╝

dataflow:>app info log --type sink
Information about sink application 'log':
Version: '1.2.0.RELEASE':
Default application version: 'true':
Resource URI: docker://springcloudstream/log-sink-rabbit:1.2.0.RELEASE
╔══════════════════════════════╤══════════════════════════════╤══════════════════════════════╤══════════════════════════════╗
║         Option Name          │         Description          │           Default            │             Type             ║
╠══════════════════════════════╪══════════════════════════════╪══════════════════════════════╪══════════════════════════════╣
║log.name                      │The name of the logger to use.│<none>                        │java.lang.String              ║
║log.level                     │The level at which to log     │<none>                        │org.springframework.integratio║
║                              │messages.                     │                              │n.handler.LoggingHandler$Level║
║log.expression                │A SpEL expression (against the│payload                       │java.lang.String              ║
║                              │incoming message) to evaluate │                              │                              ║
║                              │as the logged message.        │                              │                              ║
╚══════════════════════════════╧══════════════════════════════╧══════════════════════════════╧══════════════════════════════╝
----
====

The remainder of this chapter describes the process for deploying streams with Skipper.

. Create a stream.
+
The following example shows how to create a stream:
+
====
[source]
----
dataflow:>stream create mystream --definition "time | log"
Created new stream 'mystream'
----
====

. Deploy the stream.
+
The following example shows how to deploy the stream:
+
====
[source]
----
dataflow:>stream deploy mysteam --platformName minikube
Deployment request has been sent for stream 'mystream'
----
====
+
NOTE:While deploying the stream, we supply `--platformName`, which indicates the platform repository (in this case, `minikube`) to
use when deploying the stream applications with Skipper.

. List the pods.
+
The following command (with output) shows how to list the pods:
+
====
[source,console,options=nowrap]
----
$ kubectl get pods
NAME                              READY     STATUS    RESTARTS   AGE
mystream-log-v1-0-2k4r8             1/1       Running   0          2m
mystream-time-v1-qhdqq              1/1       Running   0          2m
mysql-777890292-z0dsw          1/1       Running   0          49m
rabbitmq-317767540-2qzrr       1/1       Running   0          49m
redis-4054078334-37m0l         1/1       Running   0          49m
scdf-server-2734071167-bjd3g   1/1       Running   0          12m
skipper-2408247821-50z31       1/1       Running   0          15m

...
...
----
====

. Verify the logs.
+
The followig example shows how to make sure that the values you expect appear in the logs:
+
====
[source,console,options=nowrap]
----
$ kubectl logs -f mystream-log-v1-0-2k4r8
...
...
2017-10-30 22:59:04.966  INFO 1 --- [ mystream.time.mystream-1] log-sink                                 : 10/30/17 22:59:04
2017-10-30 22:59:05.968  INFO 1 --- [ mystream.time.mystream-1] log-sink                                 : 10/30/17 22:59:05
2017-10-30 22:59:07.000  INFO 1 --- [ mystream.time.mystream-1] log-sink                                 : 10/30/17 22:59:06
----
====

. Verify the stream history.
+
The following example (with output) shows how to display the stream history, so that you can verify its content:
+
====
[source,console,options=nowrap]
----
dataflow:>stream history --name mystream
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║1      │Mon Oct 30 16:18:28 PDT 2017│DEPLOYED│mystream    │1.0.0          │Install complete║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
----
====

. Verify the package manifest.
+
The `log-sink` should be at 1.2.0.RELEASE. The following example (with output) shows how to display the package manifest so that you can ensure the version of the `log-sink` application:
+
====
[source,yml,options=nowrap]
----
dataflow:>stream manifest --name mystream

---
# Source: log.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "log"
spec:
  resource: "docker:springcloudstream/log-sink-rabbit"
  resourceMetadata: "docker:springcloudstream/log-sink-rabbit:jar:metadata:1.2.0.RELEASE"
  version: "1.2.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "log"
    "spring.cloud.stream.metrics.key": "mystream.log.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.input.group": "mystream"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.dataflow.stream.name": "mystream"
    "spring.cloud.dataflow.stream.app.type": "sink"
    "spring.cloud.stream.bindings.input.destination": "mystream.time"
  deploymentProperties:
    "spring.cloud.deployer.group": "mystream"

---
# Source: time.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "time"
spec:
  resource: "docker:springcloudstream/time-source-rabbit"
  resourceMetadata: "docker:springcloudstream/time-source-rabbit:jar:metadata:1.3.0.RELEASE"
  version: "1.3.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "time"
    "spring.cloud.stream.metrics.key": "mystream.time.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.output.producer.requiredGroups": "mystream"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.stream.bindings.output.destination": "mystream.time"
    "spring.cloud.dataflow.stream.name": "mystream"
    "spring.cloud.dataflow.stream.app.type": "source"
  deploymentProperties:
    "spring.cloud.deployer.group": "mystream"
----
====

. Register the `log-sink` application version 1.3.0.RELEASE and update your stream to use it
+
The following example (with output after each command) shows how to register the `log-sink` application and update its version:
+
====
[source,console,options=nowrap]
----
dataflow:>app register --name log --type sink --uri docker:springcloudstream/log-sink-rabbit:1.3.0.RELEASE --force
Successfully registered application 'sink:log'

dataflow:>stream update --name mystream --properties version.log=1.3.0.RELEASE
Update request has been sent for stream 'mystream'
----
====
+

. List the pods again.
+
The following example (with output) shows how to list the pods, so that you can see your application in the list:
+
====
[source,console,options=nowrap]
----
$ kubectl get pods
NAME                              READY     STATUS        RESTARTS   AGE
mystream-log-v1-0-2k4r8        1/1       Terminating   0          3m
mystream-log-v2-0-fjnlt        0/1       Running       0          9s
mystream-time-v1-qhdqq         1/1       Running       0          3m
mysql-777890292-z0dsw          1/1       Running       0          51m
rabbitmq-317767540-2qzrr       1/1       Running       0          51m
redis-4054078334-37m0l         1/1       Running       0          51m
scdf-server-2734071167-bjd3g   1/1       Running       0          14m
skipper-2408247821-50z31       1/1       Running       0          16m

...
...
----
====

NOTE: The list shows two versions of the `log-sink` applications. The `mystream-log-v1-0-2k4r8` pod is going down and the
newly spawned `mystream-log-v2-0-fjnlt` pod is bootstrapping. The version number is incremented and the version-number
(`v2`) is included in the new application name.

. Once the new pod is up and running, you can verify the logs.
+
The following example shows how to display the logs so that you can verify their content:
+
====
[source,console,options=nowrap]
----
$ kubectl logs -f mystream-log-v2-0-fjnlt
...
...
2017-10-30 23:24:30.016  INFO 1 --- [ mystream.time.mystream-1] log-sink                                 : 10/30/17 23:24:30
2017-10-30 23:24:31.017  INFO 1 --- [ mystream.time.mystream-1] log-sink                                 : 10/30/17 23:24:31
2017-10-30 23:24:32.018  INFO 1 --- [ mystream.time.mystream-1] log-sink                                 : 10/30/17 23:24:32
----
====

. View the updated package manifest persisted in Skipper. You should now see `log-sink` at 1.3.0.RELEASE.
+
The following example (with output) shows how to view the updated package manifest:
+
====
[source,yml,options=nowrap]
----
dataflow:>stream manifest --name mystream

---
# Source: log.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "log"
spec:
  resource: "docker:springcloudstream/log-sink-rabbit"
  resourceMetadata: "docker:springcloudstream/log-sink-rabbit:jar:metadata:1.3.0.RELEASE"
  version: "1.3.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "log"
    "spring.cloud.stream.metrics.key": "mystream.log.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.input.group": "mystream"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.dataflow.stream.name": "mystream"
    "spring.cloud.dataflow.stream.app.type": "sink"
    "spring.cloud.stream.bindings.input.destination": "mystream.time"
  deploymentProperties:
    "spring.cloud.deployer.group": "mystream"
    "spring.cloud.deployer.count": "1"

---
# Source: time.yml
apiVersion: skipper.spring.io/v1
kind: SpringCloudDeployerApplication
metadata:
  "name": "time"
spec:
  resource: "docker:springcloudstream/time-source-rabbit"
  resourceMetadata: "docker:springcloudstream/time-source-rabbit:jar:metadata:1.3.0.RELEASE"
  version: "1.3.0.RELEASE"
  applicationProperties:
    "spring.metrics.export.triggers.application.includes": "integration**"
    "spring.cloud.dataflow.stream.app.label": "time"
    "spring.cloud.stream.metrics.key": "mystream.time.${spring.cloud.application.guid}"
    "spring.cloud.stream.bindings.output.producer.requiredGroups": "mystream"
    "spring.cloud.stream.metrics.properties": "spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*"
    "spring.cloud.stream.bindings.applicationMetrics.destination": "metrics"
    "spring.cloud.stream.bindings.output.destination": "mystream.time"
    "spring.cloud.dataflow.stream.name": "mystream"
    "spring.cloud.dataflow.stream.app.type": "source"
  deploymentProperties:
    "spring.cloud.deployer.group": "mystream"
----
====

. Verify stream history for the latest updates.
+
The following example (with output) shows how to display the version history of your stream so that you can verify the version:
+
====
[source,console,options=nowrap]
----
dataflow:>stream history --name mystream
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║2      │Mon Oct 30 16:21:55 PDT 2017│DEPLOYED│mystream    │1.0.0          │Upgrade complete║
║1      │Mon Oct 30 16:18:28 PDT 2017│DELETED │mystream    │1.0.0          │Delete complete ║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
----
====

== Rolling back to a Previous Version

Skipper includes a `rollback` command so that you can roll back to a previous version.
The following example (with output) shows how to use it:

====
[source,console,options=nowrap]
----
dataflow:>stream rollback --name mystream
Rollback request has been sent for the stream 'mystream'

...
...

dataflow:>stream history --name mystream
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║3      │Mon Oct 30 16:22:51 PDT 2017│DEPLOYED│mystream    │1.0.0          │Upgrade complete║
║2      │Mon Oct 30 16:21:55 PDT 2017│DELETED │mystream    │1.0.0          │Delete complete ║
║1      │Mon Oct 30 16:18:28 PDT 2017│DELETED │mystream    │1.0.0          │Delete complete ║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
----
====
